name: Deploy Manim-Slides to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: conda-incubator/setup-miniconda@v3
      with:
        channels: conda-forge
        auto-update-conda: true
        python-version: 3.12.7

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential python3-dev libcairo2-dev libpango1.0-dev ffmpeg
        sudo apt-get install -y texlive texlive-latex-extra
        conda install -c conda-forge manim
        pipx install -U "manim-slides[pyside6-full]"

    # Step 4: Generate Manim-Slides HTML
    - name: Generate Manim-Slides HTML
      run: |
        mkdir -p slides_output
        make

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./slides_output
        destination_dir: .
