name: Deploy Manim-Slides to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          build-essential python3-dev libcairo2-dev libpango1.0-dev ffmpeg  \
          texlive texlive-latex-extra texlive-science

    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        channels: conda-forge
        auto-update-conda: true
        python-version: 3.12.7

    # Step 3: Install dependencies
    - name: Install python dependencies
      run: |
        conda install -c conda-forge -y manim
        sudo pip install meson ninja
        pip install -U "manim-slides[pyside6-full]"

    # Step 4: Generate Manim-Slides HTML
    - name: Generate Manim-Slides HTML
      run: |
        mkdir -p slides_output
        make

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./slides_output
        destination_dir: .
